# curl -v -XPOST -H "content-type: application/json" -d '{"apelido" : "xpto", "nome" : "xpto xpto", "nascimento" : "2000-01-01", "stack": null}' "http://localhost:9999/pessoas"
POST http://localhost:9999/pessoas
Content-Type: application/json

{
  "apelido": "asdasdad",
  "nome": "xpto xpto",
  "nascimento": "2000-01-01",
  "stack": ["teste"]
}

###

